### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by unlight** [stormwarning/cz-adapter-eslint#1]
Subj.

**Comment by stormwarning** [comment]
Hey, I can for sure publish this package. However, I'm afraid I've kind of ignored this package a bit since first starting on it. Have you tried it out to see if it works for you?

**Comment by unlight** [comment]
> Have you tried it out to see if it works for you?

Yes. It works for me.

**Comment by stormwarning** [comment]
Great! I should be able to get this up on npm in a little bit here 👍

**Comment by stormwarning** [comment]
0.1.0 is [available now on npm](https://www.npmjs.com/package/cz-adapter-eslint)

**Comment by unlight** [comment]
Sorry, but you published source (non-transiled) js version.
That why I am asking to publish to npm.
Without transpile, publishing to npm make no sense, because same result I can get by installing `stormwarning/cz-adapter-eslint`.

**Comment by stormwarning** [comment]
Riiiight, right.

**Comment by stormwarning** [comment]
There, npm should deliver the transpiled module now, in all three module flavours. Let me know if you still have problems using the package 👍

**Comment by unlight** [comment]
Thanks, but still it's few minor issues.
1. You are useing microbundle and it's made bundle and minified it (usually it is not nessesary for node)
2. Property main is missing in `package.json`

I've created pull request to fix these issues.

**Comment by stormwarning** [comment]
Thanks for the PR! New version published.
