### ISSUE TITLE
Remove scope from eslint style commits

### ISSUE THREAD

**Issue by ivandov** [stormwarning/cz-adapter-eslint#3]
As per the [conventional-changelog-eslint](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint) examples, it seems that a scope is not needed for eslint commits. 

Providing a scope causes tools like semantic-release to not correctly pickup version number changes. 

I believe at the very least, this logic needs to be removed from `src/engine.js`
```
{
     type: 'input',
     name: 'scope',
     message: 'What is the scope of this change (e.g. component or file name)? (press enter to skip)\n',
},
```

**Comment by ivandov** [comment]
I would send in a PR, but I wanted to open the discussion on whether or not I'm misunderstanding the eslint standards.

**Comment by Berkmann18** [comment]
The scope is indeed not part of ESLint's commit convention which also specifies that the `fix #xy` is mentioned in the title like so: `Fix: Lorem ipsum (fix #9999)` but this adapter doesn't make commitizen follow that.
And regarding the question about related issues, it's not part of that convention as well (although it wouldn't be an issue for mentioning indirect or referenced issues).

In any case, I'm happy to help.

**Comment by ivandov** [comment]
I have forked off this repo a while back to remove the scope. With the lack of response from the original author, it may make sense to publish an updated npm package with a different name if you'd like to make further changes. 

https://github.com/ivandov/cz-adapter-eslint

**Comment by Berkmann18** [comment]
@ivandov Have you submitted a PR for it on this repo tho?
I'll have a look at yours and contribute to it.

**Comment by stormwarning** [comment]
Closed in #5

**Comment by stormwarning** [comment]
Thanks for the help @ivandov and @Berkmann18!

**Comment by ivandov** [comment]
@stormwarning I will submit a PR for the removal of the scope tag... PR #5 did not address that.

**Comment by Berkmann18** [comment]
You're welcome!.
Happy to help 😄 !
